name: BactVarMiner-CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  schedule:
    - cron:  '1 1 1 * *'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Ubuntu dependencies
      run: |
        sudo apt-get update
        # sudo apt-get install
        python --version
        pip install -U pip
        pip install -U pytest

        wget https://github.com/gtonkinhill/panaroo_test_data/releases/download/v0.0.2/travis_test_data.zip
        unzip travis_test_data.zip

    - name: Install Python dependencies
      run:
        pip install -r requirements.txt
        pip3 install -e . ## install BactVarMiner (+ dependencies)

    #- name: Validation tests with PyTest
      #run:
        ## Add tests here
        ## By default pytest discovers tests in files named test_*.py or *_test.py
